export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	EDIT_USER: 'EDIT_USER',
	LOAD_CATEGORIES: 'LOAD_CATEGORIES',
	ADD_CATEGORY: 'ADD_CATEGORY',
	EDIT_CATEGORY: 'EDIT_CATEGORY',
	REMOVE_CATEGORY: 'REMOVE_CATEGORY',
	LOAD_INVOICES: 'LOAD_INVOICES',
	ADD_INVOICE: 'ADD_INVOICE',
	EDIT_INVOICE: 'EDIT_INVOICE',
	REMOVE_INVOICE: 'REMOVE_INVOICE',
	RESET_STATE: 'RESET_STATE',
};
